var num=77.1234;
 var val = num.toExponential(); 
 console.log("num.toExponential() is : "+ val ); 
 val = num.toExponential(4); 
 console.log("num.toExponential(4) is : " + val );  
 val = num.toExponential(2); 
 console.log("num.toExponential(2) is : " + val); 
 val = 77.1234.toExponential(); 
 console.log("77.1234.toExponential()is : " + val ); 
 val = 77.1234.toExponential(); 
 console.log("77 .toExponential() is : " + val);